"""us_market_expansion

Revision ID: 8ae72374b022
Revises: add_mission_progress
Create Date: 2026-02-21 13:49:35.984072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ae72374b022'
down_revision = 'add_mission_progress'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ENUM 타입이 이미 존재하는 경우를 대비하여 IF NOT EXISTS 처리
    # PostgreSQL에서는 CREATE TYPE IF NOT EXISTS를 직접 지원하지 않으므로
    # DO 블록을 사용하여 안전하게 생성
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE merchant AS ENUM ('AMAZON', 'CHEWY', 'PETCO', 'PETSMART', 'WALMART', 'TARGET', 'BRAND', 'COUPANG', 'NAVER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE stockstatus AS ENUM ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'UNAVAILABLE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE weightunit AS ENUM ('KG', 'LB');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE sizeunit AS ENUM ('KG', 'LB', 'OZ', 'G');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE lifestage AS ENUM ('ALL_LIFE_STAGES', 'GROWTH', 'ADULT_MAINTENANCE', 'SENIOR');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.create_table('product_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('merchant', postgresql.ENUM('AMAZON', 'CHEWY', 'PETCO', 'PETSMART', 'WALMART', 'TARGET', 'BRAND', 'COUPANG', 'NAVER', name='merchant', create_type=False), nullable=False),
    sa.Column('stock_status', postgresql.ENUM('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'UNAVAILABLE', name='stockstatus', create_type=False), nullable=False),
    sa.Column('zip_code_restriction', sa.String(length=20), nullable=True),
    sa.Column('delivery_time_days', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_availability_product_merchant', 'product_availability', ['product_id', 'merchant'], unique=False)
    op.create_index(op.f('ix_product_availability_product_id'), 'product_availability', ['product_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('merchant', postgresql.ENUM('AMAZON', 'CHEWY', 'PETCO', 'PETSMART', 'WALMART', 'TARGET', 'BRAND', 'COUPANG', 'NAVER', name='merchant', create_type=False), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('top_reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_rating BETWEEN 1.0 AND 5.0', name='product_reviews_rating_check'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_reviews_product_merchant', 'product_reviews', ['product_id', 'merchant'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_table('pet_current_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('feed_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meals_per_day', sa.SmallInteger(), nullable=True),
    sa.Column('daily_amount_level', sa.String(length=10), nullable=True),
    sa.Column('treats_level', sa.String(length=10), nullable=True),
    sa.Column('estimated_days_per_bag', sa.Integer(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', name='chk_ended_after_started'),
    sa.CheckConstraint('estimated_days_per_bag IS NULL OR estimated_days_per_bag BETWEEN 1 AND 365', name='chk_estimated_days'),
    sa.CheckConstraint('meals_per_day IS NULL OR meals_per_day BETWEEN 1 AND 4', name='chk_meals_per_day'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pcf_pet_active', 'pet_current_foods', ['pet_id', 'is_active'], unique=False)
    op.create_index('idx_pcf_pet_feedtype_active', 'pet_current_foods', ['pet_id', 'feed_type', 'is_active'], unique=False)
    op.create_index('idx_pcf_product_active', 'pet_current_foods', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_pet_current_foods_pet_id'), 'pet_current_foods', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_current_foods_product_id'), 'pet_current_foods', ['product_id'], unique=False)
    op.create_index('uq_pcf_pet_main_active', 'pet_current_foods', ['pet_id'], unique=True, postgresql_where=sa.text("is_active = true AND feed_type = 'MAIN'"))
    op.create_index('uq_pcf_pet_sub_active', 'pet_current_foods', ['pet_id'], unique=True, postgresql_where=sa.text("is_active = true AND feed_type = 'SUB'"))
    op.drop_index('idx_alert_events_alert_time', table_name='alert_events')
    op.create_index('idx_alert_events_alert_time', 'alert_events', ['alert_id', 'sent_at'], unique=False, postgresql_ops={'sent_at': 'DESC'})
    
    # Step 1: Add display_name_en columns as nullable first
    op.add_column('allergen_codes', sa.Column('display_name_en', sa.String(length=50), nullable=True))
    op.add_column('claim_codes', sa.Column('display_name_en', sa.String(length=50), nullable=True))
    op.add_column('health_concern_codes', sa.Column('display_name_en', sa.String(length=50), nullable=True))
    
    # Step 2: Update existing rows with English translations
    # For allergen_codes: use common English allergen names
    op.execute("""
        UPDATE allergen_codes 
        SET display_name_en = CASE code
            WHEN 'BEEF' THEN 'Beef'
            WHEN 'CHICKEN' THEN 'Chicken'
            WHEN 'PORK' THEN 'Pork'
            WHEN 'DUCK' THEN 'Duck'
            WHEN 'LAMB' THEN 'Lamb'
            WHEN 'FISH' THEN 'Fish'
            WHEN 'EGG' THEN 'Egg'
            WHEN 'DAIRY' THEN 'Dairy'
            WHEN 'WHEAT' THEN 'Wheat/Gluten'
            WHEN 'CORN' THEN 'Corn'
            WHEN 'SOY' THEN 'Soy'
            ELSE INITCAP(REPLACE(code, '_', ' '))
        END
        WHERE display_name_en IS NULL
    """)
    
    # For claim_codes: use code as fallback (most claim codes are already in English)
    op.execute("""
        UPDATE claim_codes 
        SET display_name_en = COALESCE(display_name_en, INITCAP(REPLACE(code, '_', ' ')))
        WHERE display_name_en IS NULL
    """)
    
    # For health_concern_codes: use code as fallback
    op.execute("""
        UPDATE health_concern_codes 
        SET display_name_en = COALESCE(display_name_en, INITCAP(REPLACE(code, '_', ' ')))
        WHERE display_name_en IS NULL
    """)
    
    # Step 3: Make columns NOT NULL
    op.alter_column('allergen_codes', 'display_name_en', nullable=False)
    op.alter_column('claim_codes', 'display_name_en', nullable=False)
    op.alter_column('health_concern_codes', 'display_name_en', nullable=False)
    
    # Add substantiation_required column (this one can be added directly with default)
    op.add_column('claim_codes', sa.Column('substantiation_required', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index('idx_clicks_product_time', table_name='outbound_clicks')
    op.create_index('idx_clicks_product_time', 'outbound_clicks', ['product_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index('idx_clicks_user_time', table_name='outbound_clicks')
    op.create_index('idx_clicks_user_time', 'outbound_clicks', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    # Step 1: Add new columns (nullable first)
    op.add_column('pets', sa.Column('weight_numeric', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pets', sa.Column('weight_unit', postgresql.ENUM('KG', 'LB', name='weightunit', create_type=False), nullable=True))
    
    # Step 2: Migrate existing weight_kg data to weight_numeric (convert kg to lb)
    # weight_kg is in kg, weight_numeric should be in lb (US market default)
    # 1 kg = 2.20462 lb
    op.execute("""
        UPDATE pets 
        SET weight_numeric = weight_kg * 2.20462,
            weight_unit = 'LB'
        WHERE weight_kg IS NOT NULL
    """)
    
    # Step 3: Make columns NOT NULL
    op.alter_column('pets', 'weight_numeric', nullable=False)
    op.alter_column('pets', 'weight_unit', nullable=False, server_default='LB')
    
    # Step 4: Drop old column
    op.drop_column('pets', 'weight_kg')
    op.drop_index('idx_price_snapshots_offer_time', table_name='price_snapshots')
    op.create_index('idx_price_snapshots_offer_time', 'price_snapshots', ['offer_id', 'captured_at'], unique=False, postgresql_ops={'captured_at': 'DESC'})
    op.add_column('product_claims', sa.Column('substantiation_note', sa.Text(), nullable=True))
    op.add_column('product_ingredient_profiles', sa.Column('order_by_weight', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Convert updated_at from VARCHAR to TIMESTAMP WITH TIME ZONE for product_ingredient_profiles
    # Step 1: Drop the old default (VARCHAR type)
    op.execute("""
        ALTER TABLE product_ingredient_profiles 
        ALTER COLUMN updated_at DROP DEFAULT
    """)
    # Step 2: Update any 'now()' string values to actual timestamps
    op.execute("""
        UPDATE product_ingredient_profiles 
        SET updated_at = now()::text 
        WHERE updated_at = 'now()' OR updated_at = '''now()''::character varying'
    """)
    # Step 3: Convert the column type
    op.execute("""
        ALTER TABLE product_ingredient_profiles 
        ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE 
        USING updated_at::timestamp with time zone
    """)
    # Step 4: Set the new default (TIMESTAMP type)
    op.execute("""
        ALTER TABLE product_ingredient_profiles 
        ALTER COLUMN updated_at SET DEFAULT now()
    """)
    
    op.add_column('product_nutrition_facts', sa.Column('total_dietary_fiber_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('product_nutrition_facts', sa.Column('kcal_per_cup', sa.Integer(), nullable=True))
    op.add_column('product_nutrition_facts', sa.Column('serving_size_cup', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('product_nutrition_facts', sa.Column('aafco_nutritional_adequacy', sa.Text(), nullable=True))
    op.add_column('product_nutrition_facts', sa.Column('life_stage', postgresql.ENUM('ALL_LIFE_STAGES', 'GROWTH', 'ADULT_MAINTENANCE', 'SENIOR', name='lifestage', create_type=False), server_default='ADULT_MAINTENANCE', nullable=False))
    
    # Convert updated_at from VARCHAR to TIMESTAMP WITH TIME ZONE for product_nutrition_facts
    # Step 1: Drop the old default (VARCHAR type)
    op.execute("""
        ALTER TABLE product_nutrition_facts 
        ALTER COLUMN updated_at DROP DEFAULT
    """)
    # Step 2: Update any 'now()' string values to actual timestamps
    op.execute("""
        UPDATE product_nutrition_facts 
        SET updated_at = now()::text 
        WHERE updated_at = 'now()' OR updated_at = '''now()''::character varying'
    """)
    # Step 3: Convert the column type
    op.execute("""
        ALTER TABLE product_nutrition_facts 
        ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE 
        USING updated_at::timestamp with time zone
    """)
    # Step 4: Set the new default (TIMESTAMP type)
    op.execute("""
        ALTER TABLE product_nutrition_facts 
        ALTER COLUMN updated_at SET DEFAULT now()
    """)
    op.add_column('products', sa.Column('size_value', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('size_unit', postgresql.ENUM('KG', 'LB', 'OZ', 'G', name='sizeunit', create_type=False), server_default='LB', nullable=False))
    op.drop_index('idx_products_price_per_kg', table_name='products')
    op.drop_constraint('unique_brand_name_size', 'products', type_='unique')
    op.create_unique_constraint('unique_brand_name_size', 'products', ['brand_name', 'product_name', 'size_value', 'size_unit'])
    op.drop_column('products', 'last_admin_updated_at')
    op.drop_index('idx_rec_runs_pet_time', table_name='recommendation_runs')
    op.create_index('idx_rec_runs_pet_time', 'recommendation_runs', ['pet_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rec_runs_pet_time', table_name='recommendation_runs', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_rec_runs_pet_time', 'recommendation_runs', ['pet_id', sa.text('created_at DESC')], unique=False)
    op.add_column('products', sa.Column('last_admin_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('unique_brand_name_size', 'products', type_='unique')
    op.create_unique_constraint('unique_brand_name_size', 'products', ['brand_name', 'product_name', 'size_label'])
    op.create_index('idx_products_price_per_kg', 'products', ['price_per_kg'], unique=False)
    op.drop_column('products', 'size_unit')
    op.drop_column('products', 'size_value')
    op.alter_column('product_nutrition_facts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'now()'::character varying"))
    op.drop_column('product_nutrition_facts', 'life_stage')
    op.drop_column('product_nutrition_facts', 'aafco_nutritional_adequacy')
    op.drop_column('product_nutrition_facts', 'serving_size_cup')
    op.drop_column('product_nutrition_facts', 'kcal_per_cup')
    op.drop_column('product_nutrition_facts', 'total_dietary_fiber_pct')
    op.alter_column('product_ingredient_profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'now()'::character varying"))
    op.drop_column('product_ingredient_profiles', 'order_by_weight')
    op.drop_column('product_claims', 'substantiation_note')
    op.drop_index('idx_price_snapshots_offer_time', table_name='price_snapshots', postgresql_ops={'captured_at': 'DESC'})
    op.create_index('idx_price_snapshots_offer_time', 'price_snapshots', ['offer_id', sa.text('captured_at DESC')], unique=False)
    # Step 1: Add weight_kg column (nullable first)
    op.add_column('pets', sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), nullable=True))
    
    # Step 2: Migrate weight_numeric back to weight_kg (convert lb to kg)
    # weight_numeric is in lb, weight_kg should be in kg
    # 1 lb = 0.453592 kg
    op.execute("""
        UPDATE pets 
        SET weight_kg = CASE 
            WHEN weight_unit = 'LB' THEN weight_numeric / 2.20462
            WHEN weight_unit = 'KG' THEN weight_numeric
            ELSE weight_numeric / 2.20462
        END
        WHERE weight_numeric IS NOT NULL
    """)
    
    # Step 3: Make weight_kg NOT NULL
    op.alter_column('pets', 'weight_kg', nullable=False)
    
    # Step 4: Drop new columns
    op.drop_column('pets', 'weight_unit')
    op.drop_column('pets', 'weight_numeric')
    op.drop_index('idx_clicks_user_time', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_clicks_user_time', 'outbound_clicks', ['user_id', sa.text('clicked_at DESC')], unique=False)
    op.drop_index('idx_clicks_product_time', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_clicks_product_time', 'outbound_clicks', ['product_id', sa.text('clicked_at DESC')], unique=False)
    op.drop_column('health_concern_codes', 'display_name_en')
    op.drop_column('claim_codes', 'substantiation_required')
    op.drop_column('claim_codes', 'display_name_en')
    op.drop_column('allergen_codes', 'display_name_en')
    op.drop_index('idx_alert_events_alert_time', table_name='alert_events', postgresql_ops={'sent_at': 'DESC'})
    op.create_index('idx_alert_events_alert_time', 'alert_events', ['alert_id', sa.text('sent_at DESC')], unique=False)
    op.drop_index('uq_pcf_pet_sub_active', table_name='pet_current_foods', postgresql_where=sa.text("is_active = true AND feed_type = 'SUB'"))
    op.drop_index('uq_pcf_pet_main_active', table_name='pet_current_foods', postgresql_where=sa.text("is_active = true AND feed_type = 'MAIN'"))
    op.drop_index(op.f('ix_pet_current_foods_product_id'), table_name='pet_current_foods')
    op.drop_index(op.f('ix_pet_current_foods_pet_id'), table_name='pet_current_foods')
    op.drop_index('idx_pcf_product_active', table_name='pet_current_foods')
    op.drop_index('idx_pcf_pet_feedtype_active', table_name='pet_current_foods')
    op.drop_index('idx_pcf_pet_active', table_name='pet_current_foods')
    op.drop_table('pet_current_foods')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index('idx_product_reviews_product_merchant', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('ix_product_availability_product_id'), table_name='product_availability')
    op.drop_index('idx_product_availability_product_merchant', table_name='product_availability')
    op.drop_table('product_availability')
    # ### end Alembic commands ###

